package models

import (
	"time"

	"gorm.io/gorm"
)

// The attendance for each Student and Tutorial
type Attendance struct {
	gorm.Model
	StudentID int `json:"studentId" gorm:"not null"`
	TutorialID int `json:"tutorialId" gorm:"not null"`
	Date string `json:"date" gorm:"not null"`
	Present bool `json:"present" gorm:"default:false;not null"`
}

// The attendance strings generated by the Teaching Assistant during the tutorial
type AttendanceString struct {
	gorm.Model
	Code string `json:"code" gorm:"not null"`
	TutorialID int `json:"tutorialId" gorm:"not null"`
	ExpiresAt time.Time `json:"expiresAt" gorm:"not null"`
}